version: '2'

services:
  nginx:
    image: nginx
    restart: always
    depends_on:
      - php
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/config:/etc/nginx/conf.d
      - ./nginx/static_dir:/usr/share/nginx/html
      - ./nginx/ssl:/etc/nginx/ssl
    links:
      - php
  php:
    container_name: php
    build: php
    restart: always
    ports:
      - "9000:9000"
    volumes:
      - ./php/project/:/var/www/html
      - ./php/config/:/usr/local/etc/php-fpm.d/
      - ./php/ini/php.ini:/usr/local/etc/php/php.ini
      - ./php/ini/docker-php-ext-xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
  redis:
    image: redis:5
    ports:
      - "6379"
    volumes:
      - ./redis/data:/data
  
  mongo:
    image: mongo:4
    ports:
      - "27017:27017"
    volumes:
      - ./mongo/db:/data/db
      - ./mongo/configdb:/data/configdb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: test2
  mysql:
    image: mysql:5.7
    volumes:
      - ./mysql/data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: dbname
      MYSQL_USER: user
      MYSQL_PASSWORD: pwd
