version: '2'

services:
  nginx:
    image: nginx
    restart: always
    depends_on:
      - php
    ports:
      - "8999:80"
      #- "443:443"
    volumes:
      - ./nginx/config:/etc/nginx/conf.d
      - ./php/project:/usr/share/nginx/html
      - ./nginx/ssl:/etc/nginx/ssl
    links:
      - php
    networks:
      app_net:
  php:
    container_name: php
    build: php
#    command: sleep 8888888
    restart: always
    ports:
      - "9000:9000"
    volumes:
      - ./php/project:/var/www/html
      - ./php/config/:/usr/local/etc/php-fpm.d/
      - ./php/ini/php.ini:/usr/local/etc/php/php.ini
    networks:
      app_net:
  redis:
    image: redis:5
    ports:
      - "6379"
    volumes:
      - ./redis/data:/data
    networks:
      app_net:
  
  # mongo:
  #   image: mongo:4
  #   ports:
  #     - "27017:27017"
  #   volumes:
  #     - ./mongo/db:/data/db
  #     - ./mongo/configdb:/data/configdb
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: root
  #     MONGO_INITDB_ROOT_PASSWORD: password
  #     MONGO_INITDB_DATABASE: test2
  mysql:
    image: mysql:5.7
    volumes:
      - ./mysql/data:/var/lib/mysql
    ports:
      - "3366:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      # MYSQL_DATABASE: dbname
      # MYSQL_USER: user
      # MYSQL_PASSWORD: pwd
    networks:
      app_net:
        # 固定子网ip，网段必须在子网络10.10.*.*
        ipv4_address: 10.10.10.1
networks:
    # 配置docker network
    app_net:
        driver: bridge
        ipam:
            config:
                # 子网络
                - subnet: 10.10.0.0/16
